[build]
  publish = "src/main/resources/static"

[[redirects]]
  from = "/api/*"
  to = "https://api.nexoragabon.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/actuator/*"
  to = "https://api.nexoragabon.com/actuator/:splat"
  status = 200
  force = true
